[package]
name = "ordinary_user/might-local-side"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-gatsby-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "public"
